# Set up DataBase Connection - mongoDB
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Project_UserSystemJwtTokenMongoDB

---
# Set up JWT Token
kelvin:
  app:
    jwtSecret: "7NNdHNWWbyUK0AjbPCovcFEmzTcnC9CUwzCBZvrXl7irVN2zijJCVrJHEHhzvoZpCExEwEMj9w3r1ADrzbGFGZsULb3gsSk0n7Rp2vH1MjF3VdGIlhcN0WJSGbWJ5jyp"
    jwtExpirationMs: 8640000